devices:
  - name: hichi
    type: json
    topic: tele/tasmota_FA2296/SENSOR
    sensor_id: '96_1_0'
    only_match: '1_8_0'
    mappings:
      '1_8_0': Total Consumption
      '1_8_1': Tariff 1 Consumption
      '1_8_2': Tariff 2 Consumption
      '2_8_0': Total Production
      '16_7_0': Current Consumption
      '36_7_0': Current Consumption Phase 1
      '56_7_0': Current Consumption Phase 2
      '76_7_0': Current Consumption Phase 3
      '96_1_0': Device ID
  - name: tele (Other consumption monitor)
    type: json
    topic: tele/power/SENSOR
    sensor_id: 'device_id'
    only_match: device_id
    mappings:
      device_id: Device ID
      Total_in: Total Consumption
      Total_out: Total Production
      Power_curr: Current Consumption
